### ISSUE TITLE
CSS not working properly

### ISSUE THREAD

**Issue by Bien-CV** [pinittome/pinittome.github.io#6]
Hello,

After building the app, the CSS on the main page and corkboard aren't working right.

There are no styles at all on the homepage while sticky notes don't change color in the corkboard, even though the color change request is fine from a server perspective.

I plan on contributing to this project, any help would be very appreciated.

**Comment by lloydwatkin** [comment]
Is the CSS file generated? Is there a 404 in the network panel when loading the app?

**Comment by Bien-CV** [comment]
I just realized I posted this issue on the wrong repository. I meant to post it on /pinittome/pinitto.me/ .

I will open relevant issues and send pull requests there, sorry !
